<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Action extends \App\Entity\Action implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'agentComment' => [parent::class, 'agentComment', null, 16],
        "\0".parent::class."\0".'agentValidatedAt' => [parent::class, 'agentValidatedAt', null, 16],
        "\0".parent::class."\0".'agentVisa' => [parent::class, 'agentVisa', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'logbook' => [parent::class, 'logbook', null, 16],
        "\0".parent::class."\0".'mentorComment' => [parent::class, 'mentorComment', null, 16],
        "\0".parent::class."\0".'mentorCommentedAt' => [parent::class, 'mentorCommentedAt', null, 16],
        "\0".parent::class."\0".'mentorValidatedAt' => [parent::class, 'mentorValidatedAt', null, 16],
        "\0".parent::class."\0".'mentorVisa' => [parent::class, 'mentorVisa', null, 16],
        "\0".parent::class."\0".'module' => [parent::class, 'module', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'agentComment' => [parent::class, 'agentComment', null, 16],
        'agentValidatedAt' => [parent::class, 'agentValidatedAt', null, 16],
        'agentVisa' => [parent::class, 'agentVisa', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'logbook' => [parent::class, 'logbook', null, 16],
        'mentorComment' => [parent::class, 'mentorComment', null, 16],
        'mentorCommentedAt' => [parent::class, 'mentorCommentedAt', null, 16],
        'mentorValidatedAt' => [parent::class, 'mentorValidatedAt', null, 16],
        'mentorVisa' => [parent::class, 'mentorVisa', null, 16],
        'module' => [parent::class, 'module', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
