<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ExMmL8pService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.ExMmL8p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ExMmL8p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'action' => ['privates', '.errored..service_locator.ExMmL8p.App\\Entity\\Action', NULL, 'Cannot autowire service ".service_locator.ExMmL8p": it needs an instance of "App\\Entity\\Action" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'action' => 'App\\Entity\\Action',
        ]);
    }
}
