<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MIkYJ6yService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.MIkYJ6y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MIkYJ6y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feedbackRepository' => ['privates', 'App\\Repository\\FeedbackRepository', 'getFeedbackRepositoryService', false],
        ], [
            'feedbackRepository' => 'App\\Repository\\FeedbackRepository',
        ]);
    }
}
