<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ExMmL8p.App\Entity\Action' shared service.
     *
     * @return \App\Entity\Action
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ExMmL8p": it needs an instance of "App\\Entity\\Action" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
