<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionControllerdeleteService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.ExMmL8p.App\Controller\App\Dashboard\ActionController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ExMmL8p.App\\Controller\\App\\Dashboard\\ActionController::delete()'] = ($container->privates['.service_locator.ExMmL8p'] ?? $container->load('get_ServiceLocator_ExMmL8pService'))->withContext('App\\Controller\\App\\Dashboard\\ActionController::delete()', $container);
    }
}
