<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalyseProcessusControlleranalyseProcessusService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.ha_2UGo.App\Controller\Admin\Service\AnalyseProcessusController::analyseProcessus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ha_2UGo.App\\Controller\\Admin\\Service\\AnalyseProcessusController::analyseProcessus()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'logbookRepository' => ['privates', 'App\\Repository\\LogbookRepository', 'getLogbookRepositoryService', false],
        ], [
            'logbookRepository' => 'App\\Repository\\LogbookRepository',
        ]))->withContext('App\\Controller\\Admin\\Service\\AnalyseProcessusController::analyseProcessus()', $container);
    }
}
