<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Action\ActionService' shared autowired service.
     *
     * @return \App\Services\Action\ActionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Action/ActionService.php';

        return $container->privates['App\\Services\\Action\\ActionService'] = new \App\Services\Action\ActionService(($container->privates['App\\Repository\\ActionRepository'] ?? self::getActionRepositoryService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
