<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\App\Dashboard\ActionController' shared autowired service.
     *
     * @return \App\Controller\App\Dashboard\ActionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/App/Dashboard/ActionController.php';

        $container->services['App\\Controller\\App\\Dashboard\\ActionController'] = $instance = new \App\Controller\App\Dashboard\ActionController(($container->privates['App\\Services\\Dashboard\\DashboardService'] ?? $container->load('getDashboardServiceService')), ($container->privates['App\\Services\\Action\\ActionService'] ?? $container->load('getActionServiceService')), ($container->privates['App\\Repository\\ModuleRepository'] ?? self::getModuleRepositoryService($container)), ($container->privates['App\\Repository\\LogbookRepository'] ?? self::getLogbookRepositoryService($container)), ($container->privates['App\\Repository\\ActionRepository'] ?? self::getActionRepositoryService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\App\\Dashboard\\ActionController', $container));

        return $instance;
    }
}
