<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckMigrationCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\CheckMigrationCommand' shared autowired service.
     *
     * @return \App\Command\CheckMigrationCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CheckMigrationCommand.php';

        $container->privates['App\\Command\\CheckMigrationCommand'] = $instance = new \App\Command\CheckMigrationCommand(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), (\dirname(__DIR__, 4).'/migrations'));

        $instance->setName('app:check-migration');
        $instance->setDescription('Vérifie si la table doctrine_migration_versions est vide, sinon insère la version spécifiée.');

        return $instance;
    }
}
