<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckMigrationCommand_LazyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.App\Command\CheckMigrationCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CheckMigrationCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:check-migration', [], 'Vérifie si la table doctrine_migration_versions est vide, sinon insère la version spécifiée.', false, #[\Closure(name: 'App\\Command\\CheckMigrationCommand')] fn (): \App\Command\CheckMigrationCommand => ($container->privates['App\\Command\\CheckMigrationCommand'] ?? $container->load('getCheckMigrationCommandService')));
    }
}
