<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_PublicAlias_Flasher_InstallCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.flasher.install_command' shared service.
     *
     * @return \Flasher\Symfony\Command\InstallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-flasher/flasher-symfony/Command/InstallCommand.php';

        return $container->services['console.command.public_alias.flasher.install_command'] = new \Flasher\Symfony\Command\InstallCommand(($container->privates['flasher.asset_manager'] ??= new \Flasher\Prime\Asset\AssetManager((\dirname(__DIR__, 4).'/public'), (\dirname(__DIR__, 4).'/public/vendor/flasher/manifest.json'))));
    }
}
