<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDataLoaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Datas\DataLoader' shared autowired service.
     *
     * @return \App\Services\Datas\DataLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Datas/DataLoader.php';

        return $container->privates['App\\Services\\Datas\\DataLoader'] = new \App\Services\Datas\DataLoader(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
