<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardDataProviderInterfaceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Dashboard\DashboardDataProviderInterface' shared autowired service.
     *
     * @return \App\Services\Dashboard\DashboardDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Dashboard/DashboardDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Dashboard/DashboardDataProvider.php';

        return $container->privates['App\\Services\\Dashboard\\DashboardDataProviderInterface'] = new \App\Services\Dashboard\DashboardDataProvider(($container->privates['App\\Repository\\LogbookRepository'] ?? self::getLogbookRepositoryService($container)));
    }
}
