<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindexService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.IBLvqh7.App\Controller\App\Dashboard\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dashboardService' => ['privates', 'App\\Services\\Dashboard\\DashboardService', 'getDashboardServiceService', true],
        ], [
            'dashboardService' => 'App\\Services\\Dashboard\\DashboardService',
        ]))->withContext('App\\Controller\\App\\Dashboard\\DashboardController::index()', $container);

        if (isset($container->privates['.service_locator.IBLvqh7.App\\Controller\\App\\Dashboard\\DashboardController::index()'])) {
            return $container->privates['.service_locator.IBLvqh7.App\\Controller\\App\\Dashboard\\DashboardController::index()'];
        }

        return $container->privates['.service_locator.IBLvqh7.App\\Controller\\App\\Dashboard\\DashboardController::index()'] = $instance;
    }
}
