<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardController2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\App\Dashboard\DashboardController' shared autowired service.
     *
     * @return \App\Controller\App\Dashboard\DashboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/App/Dashboard/DashboardController.php';

        $container->services['App\\Controller\\App\\Dashboard\\DashboardController'] = $instance = new \App\Controller\App\Dashboard\DashboardController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\App\\Dashboard\\DashboardController', $container));

        return $instance;
    }
}
