<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlasher_FlasherComponentService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'flasher.flasher_component' service.
     *
     * @return \Flasher\Symfony\Component\FlasherComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/php-flasher/flasher-symfony/Component/FlasherComponent.php';

        $container->factories['service_container']['flasher.flasher_component'] = function ($container) {
            return new \Flasher\Symfony\Component\FlasherComponent();
        };

        return $container->factories['service_container']['flasher.flasher_component']($container);
    }
}
