<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedbackServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Admin\Feedbacks\FeedbackService' shared autowired service.
     *
     * @return \App\Services\Admin\Feedbacks\FeedbackService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/FeedbackServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Feedbacks/FeedbackService.php';

        return $container->privates['App\\Services\\Admin\\Feedbacks\\FeedbackService'] = new \App\Services\Admin\Feedbacks\FeedbackService(($container->privates['App\\Repository\\FeedbackRepository'] ?? self::getFeedbackRepositoryService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
