<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedbackControllerreviewService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.3i9vK9m.App\Controller\App\Dashboard\FeedbackController::review()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feedback' => ['privates', '.errored..service_locator.3i9vK9m.App\\Entity\\Feedback', NULL, 'Cannot autowire service ".service_locator.3i9vK9m": it needs an instance of "App\\Entity\\Feedback" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'feedback' => 'App\\Entity\\Feedback',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\App\\Dashboard\\FeedbackController::review()', $container);

        if (isset($container->privates['.service_locator.3i9vK9m.App\\Controller\\App\\Dashboard\\FeedbackController::review()'])) {
            return $container->privates['.service_locator.3i9vK9m.App\\Controller\\App\\Dashboard\\FeedbackController::review()'];
        }

        return $container->privates['.service_locator.3i9vK9m.App\\Controller\\App\\Dashboard\\FeedbackController::review()'] = $instance;
    }
}
