<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportUsersCommand_LazyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.App\Command\ImportUsersCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ImportUsersCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:import-users', [], 'Importe les utilisateurs depuis un fichier JSON d\'export PHPMyAdmin', false, #[\Closure(name: 'App\\Command\\ImportUsersCommand')] fn (): \App\Command\ImportUsersCommand => ($container->privates['App\\Command\\ImportUsersCommand'] ?? $container->load('getImportUsersCommandService')));
    }
}
