<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogbookTemplateServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Logbook\LogbookTemplateService' shared autowired service.
     *
     * @return \App\Services\Logbook\LogbookTemplateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Logbook/LogbookTemplateService.php';

        return $container->privates['App\\Services\\Logbook\\LogbookTemplateService'] = new \App\Services\Logbook\LogbookTemplateService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Services\\Logbook\\LogbookReplacementService'] ?? $container->load('getLogbookReplacementServiceService')));
    }
}
