<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogbookDataProviderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Admin\Logbooks\LogbookDataProvider' shared autowired service.
     *
     * @return \App\Services\Admin\Logbooks\LogbookDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/LogbookDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Logbooks/LogbookDataProvider.php';

        return $container->privates['App\\Services\\Admin\\Logbooks\\LogbookDataProvider'] = new \App\Services\Admin\Logbooks\LogbookDataProvider(($container->privates['App\\Repository\\LogbookRepository'] ?? self::getLogbookRepositoryService($container)), ($container->privates['App\\Repository\\ActionRepository'] ?? self::getActionRepositoryService($container)));
    }
}
