<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogbookCrudControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\Logbook\LogbookCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\Logbook\LogbookCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/CrudControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractCrudController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/Logbook/LogbookCrudController.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['App\\Controller\\Admin\\Logbook\\LogbookCrudController'])) {
            return $container->services['App\\Controller\\Admin\\Logbook\\LogbookCrudController'];
        }

        $instance = new \App\Controller\Admin\Logbook\LogbookCrudController(($container->privates['App\\Services\\Logbook\\LogbookThemeService'] ?? self::getLogbookThemeServiceService($container)), $a, ($container->privates['App\\Repository\\ActionRepository'] ?? self::getActionRepositoryService($container)));

        if (isset($container->services['App\\Controller\\Admin\\Logbook\\LogbookCrudController'])) {
            return $container->services['App\\Controller\\Admin\\Logbook\\LogbookCrudController'];
        }

        $container->services['App\\Controller\\Admin\\Logbook\\LogbookCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.t0DHw4I'] ?? $container->load('get_ServiceLocator_T0DHw4IService'))->withContext('App\\Controller\\Admin\\Logbook\\LogbookCrudController', $container));

        return $instance;
    }
}
