<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogbookNameSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\LogbookNameSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\LogbookNameSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/LogbookNameSubscriber.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventSubscriber\\LogbookNameSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\LogbookNameSubscriber'];
        }

        $instance = new \App\EventSubscriber\LogbookNameSubscriber($a);

        if (isset($container->privates['App\\EventSubscriber\\LogbookNameSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\LogbookNameSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\LogbookNameSubscriber'] = $instance;
    }
}
