<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogbookService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iuuhNp4.App\Entity\Logbook' shared service.
     *
     * @return \App\Entity\Logbook
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.iuuhNp4": it needs an instance of "App\\Entity\\Logbook" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
