<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogbookTemplateCrudControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\Logbook_Models\LogbookTemplateCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\Logbook_Models\LogbookTemplateCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/CrudControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractCrudController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/Logbook_Models/LogbookTemplateCrudController.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['App\\Controller\\Admin\\Logbook_Models\\LogbookTemplateCrudController'])) {
            return $container->services['App\\Controller\\Admin\\Logbook_Models\\LogbookTemplateCrudController'];
        }

        $instance = new \App\Controller\Admin\Logbook_Models\LogbookTemplateCrudController($a);

        if (isset($container->services['App\\Controller\\Admin\\Logbook_Models\\LogbookTemplateCrudController'])) {
            return $container->services['App\\Controller\\Admin\\Logbook_Models\\LogbookTemplateCrudController'];
        }

        $container->services['App\\Controller\\Admin\\Logbook_Models\\LogbookTemplateCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.t0DHw4I'] ?? $container->load('get_ServiceLocator_T0DHw4IService'))->withContext('App\\Controller\\Admin\\Logbook_Models\\LogbookTemplateCrudController', $container));

        return $instance;
    }
}
