<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentorActionTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\MentorActionType' shared autowired service.
     *
     * @return \App\Form\MentorActionType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MentorActionType.php';

        return $container->privates['App\\Form\\MentorActionType'] = new \App\Form\MentorActionType();
    }
}
