<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentorLogbookControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\App\Dashboard\Mentor\MentorLogbookController' shared autowired service.
     *
     * @return \App\Controller\App\Dashboard\Mentor\MentorLogbookController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/App/Dashboard/Mentor/MentorLogbookController.php';

        $container->services['App\\Controller\\App\\Dashboard\\Mentor\\MentorLogbookController'] = $instance = new \App\Controller\App\Dashboard\Mentor\MentorLogbookController(($container->privates['App\\Services\\Mentor\\MentorService'] ?? $container->load('getMentorServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Services\\Logbook\\LogbookProgressService'] ??= new \App\Services\Logbook\LogbookProgressService()));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\App\\Dashboard\\Mentor\\MentorLogbookController', $container));

        return $instance;
    }
}
