<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailControllersendEmailsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.I1H8UTo.App\Controller\Mail_Testing\MailController::sendEmails()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reminderService' => ['privates', 'App\\Services\\Mail\\MentorReminderEmailService', 'getMentorReminderEmailServiceService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', false],
        ], [
            'reminderService' => 'App\\Services\\Mail\\MentorReminderEmailService',
            'mailer' => '?',
        ]))->withContext('App\\Controller\\Mail_Testing\\MailController::sendEmails()', $container);

        if (isset($container->privates['.service_locator.I1H8UTo.App\\Controller\\Mail_Testing\\MailController::sendEmails()'])) {
            return $container->privates['.service_locator.I1H8UTo.App\\Controller\\Mail_Testing\\MailController::sendEmails()'];
        }

        return $container->privates['.service_locator.I1H8UTo.App\\Controller\\Mail_Testing\\MailController::sendEmails()'] = $instance;
    }
}
