<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailerServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Mail\MailerService' shared autowired service.
     *
     * @return \App\Services\Mail\MailerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Mail/MailerService.php';

        return $container->privates['App\\Services\\Mail\\MailerService'] = new \App\Services\Mail\MailerService(($container->privates['mailer.mailer'] ?? self::getMailer_MailerService($container)));
    }
}
