<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentorReminderEmailServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Mail\MentorReminderEmailService' shared autowired service.
     *
     * @return \App\Services\Mail\MentorReminderEmailService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Mail/MentorReminderEmailService.php';

        return $container->privates['App\\Services\\Mail\\MentorReminderEmailService'] = new \App\Services\Mail\MentorReminderEmailService();
    }
}
