<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgressAccessServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Admin\Progress\ProgressAccessService' shared autowired service.
     *
     * @return \App\Services\Admin\Progress\ProgressAccessService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/ProgressAccessServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Progress/ProgressAccessService.php';

        return $container->privates['App\\Services\\Admin\\Progress\\ProgressAccessService'] = new \App\Services\Admin\Progress\ProgressAccessService(($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)));
    }
}
