<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgressControllerfeedbackDetailService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.MIkYJ6y.App\Controller\Admin\Progress\ProgressController::feedbackDetail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MIkYJ6y.App\\Controller\\Admin\\Progress\\ProgressController::feedbackDetail()'] = ($container->privates['.service_locator.MIkYJ6y'] ?? $container->load('get_ServiceLocator_MIkYJ6yService'))->withContext('App\\Controller\\Admin\\Progress\\ProgressController::feedbackDetail()', $container);
    }
}
