<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgressControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\Progress\ProgressController' shared autowired service.
     *
     * @return \App\Controller\Admin\Progress\ProgressController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/Progress/ProgressController.php';

        $container->services['App\\Controller\\Admin\\Progress\\ProgressController'] = $instance = new \App\Controller\Admin\Progress\ProgressController(($container->privates['App\\Services\\Admin\\Progress\\ProgressTrackingService'] ?? $container->load('getProgressTrackingServiceService')), ($container->privates['App\\Services\\Admin\\Progress\\ProgressAccessService'] ?? $container->load('getProgressAccessServiceService')), ($container->privates['App\\Services\\Admin\\Users\\UserProgressService'] ?? $container->load('getUserProgressServiceService')), ($container->privates['App\\Services\\Admin\\Feedbacks\\FeedbackService'] ?? $container->load('getFeedbackServiceService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Admin\\Progress\\ProgressController', $container));

        return $instance;
    }
}
