<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgressTrackingServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Admin\Progress\ProgressTrackingService' shared autowired service.
     *
     * @return \App\Services\Admin\Progress\ProgressTrackingService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/ProgressTrackingServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Progress/ProgressTrackingService.php';

        return $container->privates['App\\Services\\Admin\\Progress\\ProgressTrackingService'] = new \App\Services\Admin\Progress\ProgressTrackingService(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Services\\Admin\\Logbooks\\LogbookDataProvider'] ?? $container->load('getLogbookDataProviderService')), ($container->privates['App\\Services\\Admin\\Statistics\\StatisticsService'] ?? $container->load('getStatisticsServiceService')), ($container->privates['App\\Services\\Admin\\Themes\\ThemeProgressService'] ?? $container->load('getThemeProgressServiceService')), ($container->privates['App\\Services\\Admin\\Progress\\ProgressAccessService'] ?? $container->load('getProgressAccessServiceService')), ($container->privates['App\\Services\\Logbook\\LogbookProgressService'] ??= new \App\Services\Logbook\LogbookProgressService()), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
