<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessDeletionRequestsCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\ProcessDeletionRequestsCommand' shared autowired service.
     *
     * @return \App\Command\ProcessDeletionRequestsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ProcessDeletionRequestsCommand.php';

        $container->privates['App\\Command\\ProcessDeletionRequestsCommand'] = $instance = new \App\Command\ProcessDeletionRequestsCommand(($container->privates['App\\Services\\RGPD\\AccountDeletionService'] ?? self::getAccountDeletionServiceService($container)));

        $instance->setName('app:process-deletion-requests');
        $instance->setDescription('Traite les demandes de suppression de compte expirées (délai de 48h dépassé)');

        return $instance;
    }
}
