<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouting_Loader_Attribute_ServicesService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'routing.loader.attribute.services' shared service.
     *
     * @return \Symfony\Component\Routing\Loader\AttributeServicesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/LoaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/routing/Loader/AttributeServicesLoader.php';

        return $container->privates['routing.loader.attribute.services'] = new \Symfony\Component\Routing\Loader\AttributeServicesLoader(['App\\Controller\\Admin\\Logbook\\LogbookCrudController', 'App\\Controller\\Admin\\Progress\\ProgressController', 'App\\Controller\\Admin\\Service\\AnalyseProcessusController', 'App\\Controller\\Admin\\User\\UserLogbookController', 'App\\Controller\\App\\AccountDeletionPublicController', 'App\\Controller\\App\\Dashboard\\ActionController', 'App\\Controller\\App\\Dashboard\\DashboardController', 'App\\Controller\\App\\Dashboard\\FeedbackController', 'App\\Controller\\App\\Dashboard\\Mentor\\MentorDashboardController', 'App\\Controller\\App\\Dashboard\\Mentor\\MentorLogbookController', 'App\\Controller\\App\\HomeController', 'App\\Controller\\App\\LegalController', 'App\\Controller\\App\\Pages\\PagesController', 'App\\Controller\\Mail_Testing\\MailController', 'App\\Controller\\Security\\ResetPasswordController', 'App\\Controller\\Security\\SecurityController', 'App\\Controller\\User\\AccountDeletionController', 'App\\Controller\\User\\UserDataExportController', 'App\\Controller\\User\\UserProfileController']);
    }
}
