<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPasswordControllerrequestService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.db.LmRj.App\Controller\Security\ResetPasswordController::request()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', false],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'mailer' => '?',
            'translator' => '?',
        ]))->withContext('App\\Controller\\Security\\ResetPasswordController::request()', $container);

        if (isset($container->privates['.service_locator.db.LmRj.App\\Controller\\Security\\ResetPasswordController::request()'])) {
            return $container->privates['.service_locator.db.LmRj.App\\Controller\\Security\\ResetPasswordController::request()'];
        }

        return $container->privates['.service_locator.db.LmRj.App\\Controller\\Security\\ResetPasswordController::request()'] = $instance;
    }
}
