<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetMigrationVersionsCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\ResetMigrationVersionsCommand' shared autowired service.
     *
     * @return \App\Command\ResetMigrationVersionsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ResetMigrationVersionsCommand.php';

        $container->privates['App\\Command\\ResetMigrationVersionsCommand'] = $instance = new \App\Command\ResetMigrationVersionsCommand(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));

        $instance->setName('app:reset-migration-versions');
        $instance->setDescription('Supprime toutes les versions de migration de la base de données');

        return $instance;
    }
}
