<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPasswordControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Security\ResetPasswordController' shared autowired service.
     *
     * @return \App\Controller\Security\ResetPasswordController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfonycasts/reset-password-bundle/src/Controller/ResetPasswordControllerTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Security/ResetPasswordController.php';

        $container->services['App\\Controller\\Security\\ResetPasswordController'] = $instance = new \App\Controller\Security\ResetPasswordController(($container->privates['symfonycasts.reset_password.helper'] ?? $container->load('getSymfonycasts_ResetPassword_HelperService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Services\\Mail\\MailerService'] ?? $container->load('getMailerServiceService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Security\\ResetPasswordController', $container));

        return $instance;
    }
}
