<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestoreDataCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\helper\RestoreDataCommand' shared autowired service.
     *
     * @return \App\Command\helper\RestoreDataCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/helper/RestoreDataCommand.php';

        $container->privates['App\\Command\\helper\\RestoreDataCommand'] = $instance = new \App\Command\helper\RestoreDataCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:restore-data');
        $instance->setDescription('Restaure des données depuis des fichiers JSON exportés par phpMyAdmin');

        return $instance;
    }
}
