<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestoreDataCommand_LazyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.App\Command\helper\RestoreDataCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\helper\\RestoreDataCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:restore-data', [], 'Restaure des données depuis des fichiers JSON exportés par phpMyAdmin', false, #[\Closure(name: 'App\\Command\\helper\\RestoreDataCommand')] fn (): \App\Command\helper\RestoreDataCommand => ($container->privates['App\\Command\\helper\\RestoreDataCommand'] ?? $container->load('getRestoreDataCommandService')));
    }
}
