<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendMailCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\Scheduler\SendMailCommand' shared autowired service.
     *
     * @return \App\Command\Scheduler\SendMailCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Scheduler/SendMailCommand.php';

        $container->privates['App\\Command\\Scheduler\\SendMailCommand'] = $instance = new \App\Command\Scheduler\SendMailCommand(($container->privates['App\\Message\\MessageHandler\\SendReminderEmailsHandler'] ?? $container->load('getSendReminderEmailsHandlerService')), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));

        $instance->setName('app:send-mail');
        $instance->setDescription('Envoie des emails de rappel aux mentors ayant des validations en attente');

        return $instance;
    }
}
