<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendEmailReminderCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\Scheduler\SendEmailReminderCommand' shared autowired service.
     *
     * @return \App\Command\Scheduler\SendEmailReminderCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Scheduler/SendEmailReminderCommand.php';

        $container->privates['App\\Command\\Scheduler\\SendEmailReminderCommand'] = $instance = new \App\Command\Scheduler\SendEmailReminderCommand(($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container)));

        $instance->setName('app:reminder-email');
        $instance->setDescription('Planifie l\'envoie hebdomadaire des emails de rappels aux tuteurs');

        return $instance;
    }
}
