<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatisticsServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Admin\Statistics\StatisticsService' shared autowired service.
     *
     * @return \App\Services\Admin\Statistics\StatisticsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/StatisticsServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Statistics/StatisticsService.php';

        return $container->privates['App\\Services\\Admin\\Statistics\\StatisticsService'] = new \App\Services\Admin\Statistics\StatisticsService(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\FeedbackRepository'] ?? self::getFeedbackRepositoryService($container)), ($container->privates['App\\Services\\Logbook\\LogbookProgressService'] ??= new \App\Services\Logbook\LogbookProgressService()), ($container->privates['App\\Services\\Admin\\Logbooks\\LogbookDataProvider'] ?? $container->load('getLogbookDataProviderService')), ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)));
    }
}
