<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendMailCommand_LazyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.App\Command\Scheduler\SendMailCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\Scheduler\\SendMailCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:send-mail', [], 'Envoie des emails de rappel aux mentors ayant des validations en attente', false, #[\Closure(name: 'App\\Command\\Scheduler\\SendMailCommand')] fn (): \App\Command\Scheduler\SendMailCommand => ($container->privates['App\\Command\\Scheduler\\SendMailCommand'] ?? $container->load('getSendMailCommandService')));
    }
}
