<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendEmailReminderCommand_LazyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.App\Command\Scheduler\SendEmailReminderCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\Scheduler\\SendEmailReminderCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:reminder-email', [], 'Planifie l\'envoie hebdomadaire des emails de rappels aux tuteurs', false, #[\Closure(name: 'App\\Command\\Scheduler\\SendEmailReminderCommand')] fn (): \App\Command\Scheduler\SendEmailReminderCommand => ($container->privates['App\\Command\\Scheduler\\SendEmailReminderCommand'] ?? $container->load('getSendEmailReminderCommandService')));
    }
}
