<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScheduler_Provider_TaskEmailService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'scheduler.provider.task_email' shared service.
     *
     * @return \Symfony\Component\Scheduler\Schedule
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/scheduler/ScheduleProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/scheduler/Schedule.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/scheduler/Trigger/MessageProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/scheduler/RecurringMessage.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Message/RedispatchMessage.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Messenger/RunCommandMessage.php';

        $container->privates['scheduler.provider.task_email'] = $instance = new \Symfony\Component\Scheduler\Schedule();

        $instance->add(\Symfony\Component\Scheduler\RecurringMessage::cron('* 14 * * 3', new \Symfony\Component\Messenger\Message\RedispatchMessage(new \Symfony\Component\Console\Messenger\RunCommandMessage('app:send-mail'), 'async'), 'Europe/Paris'));

        return $instance;
    }
}
