<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendReminderEmailsHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Message\MessageHandler\SendReminderEmailsHandler' shared autowired service.
     *
     * @return \App\Message\MessageHandler\SendReminderEmailsHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Message/MessageHandler/SendReminderEmailsHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Mail/MentorReminderEmailService.php';

        return $container->privates['App\\Message\\MessageHandler\\SendReminderEmailsHandler'] = new \App\Message\MessageHandler\SendReminderEmailsHandler(($container->privates['App\\Services\\Logbook\\LogbookProgressService'] ??= new \App\Services\Logbook\LogbookProgressService()), ($container->privates['App\\Repository\\LogbookRepository'] ?? self::getLogbookRepositoryService($container)), ($container->privates['App\\Services\\Mail\\MentorReminderEmailService'] ??= new \App\Services\Mail\MentorReminderEmailService()), ($container->privates['mailer.mailer'] ?? self::getMailer_MailerService($container)), ($container->privates['twig'] ?? self::getTwigService($container)), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
