<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeInfo_ResolverService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'type_info.resolver' shared service.
     *
     * @return \Symfony\Component\TypeInfo\TypeResolver\TypeResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/type-info/TypeResolver/TypeResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/type-info/TypeResolver/TypeResolver.php';

        return $container->privates['type_info.resolver'] = new \Symfony\Component\TypeInfo\TypeResolver\TypeResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'string' => ['privates', 'type_info.resolver.string', 'getTypeInfo_Resolver_StringService', true],
            'ReflectionParameter' => ['privates', 'type_info.resolver.reflection_parameter.phpdoc_aware', 'getTypeInfo_Resolver_ReflectionParameter_PhpdocAwareService', true],
            'ReflectionProperty' => ['privates', 'type_info.resolver.reflection_property.phpdoc_aware', 'getTypeInfo_Resolver_ReflectionProperty_PhpdocAwareService', true],
            'ReflectionFunctionAbstract' => ['privates', 'type_info.resolver.reflection_return.phpdoc_aware', 'getTypeInfo_Resolver_ReflectionReturn_PhpdocAwareService', true],
            'ReflectionType' => ['privates', 'type_info.resolver.reflection_type', 'getTypeInfo_Resolver_ReflectionTypeService', true],
        ], [
            'string' => '?',
            'ReflectionParameter' => '?',
            'ReflectionProperty' => '?',
            'ReflectionFunctionAbstract' => '?',
            'ReflectionType' => '?',
        ]));
    }
}
