<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Repository\ThemeRepository' shared autowired service.
     *
     * @return \App\Repository\ThemeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ThemeRepository.php';

        return $container->privates['App\\Repository\\ThemeRepository'] = new \App\Repository\ThemeRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
