<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeProgressServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Admin\Themes\ThemeProgressService' shared autowired service.
     *
     * @return \App\Services\Admin\Themes\ThemeProgressService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/ThemeProgressServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Themes/ThemeProgressService.php';

        return $container->privates['App\\Services\\Admin\\Themes\\ThemeProgressService'] = new \App\Services\Admin\Themes\ThemeProgressService(($container->privates['App\\Repository\\ThemeRepository'] ?? $container->load('getThemeRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\ActionRepository'] ?? self::getActionRepositoryService($container)));
    }
}
