<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeInfo_Resolver_ReflectionReturn_PhpdocAwareService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'type_info.resolver.reflection_return.phpdoc_aware' shared service.
     *
     * @return \Symfony\Component\TypeInfo\TypeResolver\PhpDocAwareReflectionTypeResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/type-info/TypeResolver/TypeResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/type-info/TypeResolver/PhpDocAwareReflectionTypeResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/type-info/TypeResolver/StringTypeResolver.php';

        return $container->privates['type_info.resolver.reflection_return.phpdoc_aware'] = new \Symfony\Component\TypeInfo\TypeResolver\PhpDocAwareReflectionTypeResolver(($container->privates['type_info.resolver.reflection_return'] ?? $container->load('getTypeInfo_Resolver_ReflectionReturnService')), ($container->privates['type_info.resolver.string'] ??= new \Symfony\Component\TypeInfo\TypeResolver\StringTypeResolver(NULL, NULL, [])), ($container->privates['type_info.type_context_factory'] ?? $container->load('getTypeInfo_TypeContextFactoryService')));
    }
}
