<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProgressServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Admin\Users\UserProgressService' shared autowired service.
     *
     * @return \App\Services\Admin\Users\UserProgressService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/UserProgressServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Users/UserProgressService.php';

        return $container->privates['App\\Services\\Admin\\Users\\UserProgressService'] = new \App\Services\Admin\Users\UserProgressService(($container->privates['App\\Repository\\LogbookRepository'] ?? self::getLogbookRepositoryService($container)), ($container->privates['App\\Services\\Logbook\\LogbookProgressService'] ??= new \App\Services\Logbook\LogbookProgressService()), ($container->privates['App\\Services\\Admin\\Progress\\ProgressAccessService'] ?? $container->load('getProgressAccessServiceService')), ($container->privates['twig'] ?? self::getTwigService($container)), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
