<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCrudControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\User\UserCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\User\UserCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/CrudControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractCrudController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/User/UserCrudController.php';

        $a = ($container->privates['App\\Services\\Admin\\Users\\UserDeletionService'] ?? $container->load('getUserDeletionServiceService'));

        if (isset($container->services['App\\Controller\\Admin\\User\\UserCrudController'])) {
            return $container->services['App\\Controller\\Admin\\User\\UserCrudController'];
        }

        $instance = new \App\Controller\Admin\User\UserCrudController(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), $a);

        if (isset($container->services['App\\Controller\\Admin\\User\\UserCrudController'])) {
            return $container->services['App\\Controller\\Admin\\User\\UserCrudController'];
        }

        $container->services['App\\Controller\\Admin\\User\\UserCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.t0DHw4I'] ?? $container->load('get_ServiceLocator_T0DHw4IService'))->withContext('App\\Controller\\Admin\\User\\UserCrudController', $container));

        return $instance;
    }
}
