<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDataExportServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\RGPD\UserDataExportService' shared autowired service.
     *
     * @return \App\Services\RGPD\UserDataExportService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/RGPD/UserDataExportService.php';

        return $container->privates['App\\Services\\RGPD\\UserDataExportService'] = new \App\Services\RGPD\UserDataExportService(($container->privates['twig'] ?? self::getTwigService($container)), ($container->privates['App\\Repository\\LogbookRepository'] ?? self::getLogbookRepositoryService($container)), ($container->privates['App\\Repository\\ActionRepository'] ?? self::getActionRepositoryService($container)), ($container->privates['App\\Repository\\FeedbackRepository'] ?? self::getFeedbackRepositoryService($container)));
    }
}
