<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserLogbookControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\User\UserLogbookController' shared autowired service.
     *
     * @return \App\Controller\Admin\User\UserLogbookController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/User/UserLogbookController.php';

        $container->services['App\\Controller\\Admin\\User\\UserLogbookController'] = $instance = new \App\Controller\Admin\User\UserLogbookController(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\LogbookTemplateRepository'] ?? $container->load('getLogbookTemplateRepositoryService')), ($container->privates['App\\Services\\Logbook\\LogbookTemplateService'] ?? $container->load('getLogbookTemplateServiceService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Admin\\User\\UserLogbookController', $container));

        return $instance;
    }
}
