<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserSeniorityServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\User\UserSeniorityService' shared autowired service.
     *
     * @return \App\Services\User\UserSeniorityService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/User/UserSeniorityService.php';

        return $container->privates['App\\Services\\User\\UserSeniorityService'] = new \App\Services\User\UserSeniorityService();
    }
}
