<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_FingerprintCalculatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'ux.live_component.fingerprint_calculator' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Util\FingerprintCalculator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/Util/FingerprintCalculator.php';

        return $container->privates['ux.live_component.fingerprint_calculator'] = new \Symfony\UX\LiveComponent\Util\FingerprintCalculator($container->getEnv('APP_SECRET'));
    }
}
