<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_QueryStringPropsExtractorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'ux.live_component.query_string_props_extractor' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Util\RequestPropsExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/Util/RequestPropsExtractor.php';

        return $container->privates['ux.live_component.query_string_props_extractor'] = new \Symfony\UX\LiveComponent\Util\RequestPropsExtractor(($container->privates['ux.live_component.component_hydrator'] ?? $container->load('getUx_LiveComponent_ComponentHydratorService')));
    }
}
