<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_DeferLiveComponentSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'ux.live_component.defer_live_component_subscriber' shared service.
     *
     * @return \Symfony\UX\LiveComponent\EventListener\DeferLiveComponentSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/EventListener/DeferLiveComponentSubscriber.php';

        return $container->privates['ux.live_component.defer_live_component_subscriber'] = new \Symfony\UX\LiveComponent\EventListener\DeferLiveComponentSubscriber();
    }
}
