<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDataExportControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\User\UserDataExportController' shared autowired service.
     *
     * @return \App\Controller\User\UserDataExportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/User/UserDataExportController.php';

        $container->services['App\\Controller\\User\\UserDataExportController'] = $instance = new \App\Controller\User\UserDataExportController(($container->privates['App\\Services\\RGPD\\UserDataExportService'] ?? $container->load('getUserDataExportServiceService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\User\\UserDataExportController', $container));

        return $instance;
    }
}
