<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProfileControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\User\UserProfileController' shared autowired service.
     *
     * @return \App\Controller\User\UserProfileController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/User/UserProfileController.php';

        $container->services['App\\Controller\\User\\UserProfileController'] = $instance = new \App\Controller\User\UserProfileController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\User\\UserProfileController', $container));

        return $instance;
    }
}
