<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_Twig_TemplateMapperService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'ux.live_component.twig.template_mapper' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Twig\TemplateMap
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/Twig/TemplateMap.php';

        return $container->privates['ux.live_component.twig.template_mapper'] = new \Symfony\UX\LiveComponent\Twig\TemplateMap(($container->targetDir.''.'/live_components_twig_templates.map'));
    }
}
