<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDeletionServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Admin\Users\UserDeletionService' shared autowired service.
     *
     * @return \App\Services\Admin\Users\UserDeletionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Users/UserDeletionService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Services\\Admin\\Users\\UserDeletionService'])) {
            return $container->privates['App\\Services\\Admin\\Users\\UserDeletionService'];
        }

        $instance = new \App\Services\Admin\Users\UserDeletionService($a);

        if (isset($container->privates['App\\Services\\Admin\\Users\\UserDeletionService'])) {
            return $container->privates['App\\Services\\Admin\\Users\\UserDeletionService'];
        }

        return $container->privates['App\\Services\\Admin\\Users\\UserDeletionService'] = $instance;
    }
}
