<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeeklyReminderEmailServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\Mail\WeeklyReminderEmailService' shared autowired service.
     *
     * @return \App\Services\Mail\WeeklyReminderEmailService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Mail/WeeklyReminderEmailService.php';

        return $container->privates['App\\Services\\Mail\\WeeklyReminderEmailService'] = new \App\Services\Mail\WeeklyReminderEmailService(($container->privates['App\\Services\\Logbook\\LogbookProgressService'] ??= new \App\Services\Logbook\LogbookProgressService()), ($container->privates['App\\Repository\\LogbookRepository'] ?? self::getLogbookRepositoryService($container)), ($container->privates['mailer.mailer'] ?? self::getMailer_MailerService($container)), ($container->privates['twig'] ?? self::getTwigService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
