<?php

namespace ContainerKhagnyb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeeklyReminderEmailHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Message\MessageHandler\WeeklyReminderEmailHandler' shared autowired service.
     *
     * @return \App\Message\MessageHandler\WeeklyReminderEmailHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Message/MessageHandler/WeeklyReminderEmailHandler.php';

        return $container->privates['App\\Message\\MessageHandler\\WeeklyReminderEmailHandler'] = new \App\Message\MessageHandler\WeeklyReminderEmailHandler(($container->privates['App\\Services\\Mail\\WeeklyReminderEmailService'] ?? $container->load('getWeeklyReminderEmailServiceService')));
    }
}
