<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DeletionRequest extends \App\Entity\DeletionRequest implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cancellationToken' => [parent::class, 'cancellationToken', null, 16],
        "\0".parent::class."\0".'cancelledAt' => [parent::class, 'cancelledAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'processedAt' => [parent::class, 'processedAt', null, 16],
        "\0".parent::class."\0".'requestedAt' => [parent::class, 'requestedAt', null, 16],
        "\0".parent::class."\0".'requestedBy' => [parent::class, 'requestedBy', null, 16],
        "\0".parent::class."\0".'scheduledDeletionAt' => [parent::class, 'scheduledDeletionAt', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        "\0".parent::class."\0".'userInfo' => [parent::class, 'userInfo', null, 16],
        'cancellationToken' => [parent::class, 'cancellationToken', null, 16],
        'cancelledAt' => [parent::class, 'cancelledAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'processedAt' => [parent::class, 'processedAt', null, 16],
        'requestedAt' => [parent::class, 'requestedAt', null, 16],
        'requestedBy' => [parent::class, 'requestedBy', null, 16],
        'scheduledDeletionAt' => [parent::class, 'scheduledDeletionAt', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'user' => [parent::class, 'user', null, 16],
        'userInfo' => [parent::class, 'userInfo', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
