<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'actions' => [parent::class, 'actions', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'feedbacks' => [parent::class, 'feedbacks', null, 16],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null, 16],
        "\0".parent::class."\0".'hiringAt' => [parent::class, 'hiringAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'job' => [parent::class, 'job', null, 16],
        "\0".parent::class."\0".'lastLoginAt' => [parent::class, 'lastLoginAt', null, 16],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null, 16],
        "\0".parent::class."\0".'logbooks' => [parent::class, 'logbooks', null, 16],
        "\0".parent::class."\0".'mentor' => [parent::class, 'mentor', null, 16],
        "\0".parent::class."\0".'nni' => [parent::class, 'nni', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'service' => [parent::class, 'service', null, 16],
        "\0".parent::class."\0".'speciality' => [parent::class, 'speciality', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'actions' => [parent::class, 'actions', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'feedbacks' => [parent::class, 'feedbacks', null, 16],
        'firstname' => [parent::class, 'firstname', null, 16],
        'hiringAt' => [parent::class, 'hiringAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'job' => [parent::class, 'job', null, 16],
        'lastLoginAt' => [parent::class, 'lastLoginAt', null, 16],
        'lastname' => [parent::class, 'lastname', null, 16],
        'logbooks' => [parent::class, 'logbooks', null, 16],
        'mentor' => [parent::class, 'mentor', null, 16],
        'nni' => [parent::class, 'nni', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'service' => [parent::class, 'service', null, 16],
        'speciality' => [parent::class, 'speciality', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
