<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKhagnyb\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKhagnyb/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerKhagnyb.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerKhagnyb\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerKhagnyb\App_KernelTestDebugContainer([
    'container.build_hash' => 'Khagnyb',
    'container.build_id' => '2da8be13',
    'container.build_time' => 1768848322,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKhagnyb');
