<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_ZylQEtgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.ZylQEtg' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Message/MessageHandler/WeeklyReminderEmailHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Mail/WeeklyReminderEmailService.php';

        return $container->privates['.messenger.handler_descriptor.ZylQEtg'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Message\MessageHandler\WeeklyReminderEmailHandler(new \App\Services\Mail\WeeklyReminderEmailService(($container->privates['App\\Services\\Logbook\\LogbookProgressService'] ??= new \App\Services\Logbook\LogbookProgressService()), ($container->privates['App\\Repository\\LogbookRepository'] ?? self::getLogbookRepositoryService($container)), ($container->privates['mailer.mailer'] ?? self::getMailer_MailerService($container)), ($container->privates['twig'] ?? self::getTwigService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)))), []);
    }
}
