<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WysqJvgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WysqJvg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WysqJvg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'task_email' => ['privates', 'scheduler.provider.task_email', 'getScheduler_Provider_TaskEmailService', true],
        ], [
            'task_email' => 'Symfony\\Component\\Scheduler\\Schedule',
        ]);
    }
}
