<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Twig\Components\ActionForm' autowired service.
     *
     * @return \App\Twig\Components\ActionForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/ComponentWithFormTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/ValidatableComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/ActionForm.php';

        $container->factories['App\\Twig\\Components\\ActionForm'] = function ($container) {
            $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

            if (isset($container->services['App\\Twig\\Components\\ActionForm'])) {
                return $container->services['App\\Twig\\Components\\ActionForm'];
            }

            $instance = new \App\Twig\Components\ActionForm($a);

            $instance->setContainer(($container->privates['.service_locator.TJNRSaV.App\\Twig\\Components\\ActionForm'] ?? $container->load('getActionForm2Service')));
            $instance->setComponentValidator(($container->privates['Symfony\\UX\\LiveComponent\\ComponentValidator'] ?? $container->load('getComponentValidatorService')));

            return $instance;
        };

        return $container->factories['App\\Twig\\Components\\ActionForm']($container);
    }
}
