<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionForm2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TJNRSaV.App\Twig\Components\ActionForm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'));

        if (isset($container->privates['.service_locator.TJNRSaV.App\\Twig\\Components\\ActionForm'])) {
            return $container->privates['.service_locator.TJNRSaV.App\\Twig\\Components\\ActionForm'];
        }

        $instance = $a->withContext('App\\Twig\\Components\\ActionForm', $container);

        if (isset($container->privates['.service_locator.TJNRSaV.App\\Twig\\Components\\ActionForm'])) {
            return $container->privates['.service_locator.TJNRSaV.App\\Twig\\Components\\ActionForm'];
        }

        return $container->privates['.service_locator.TJNRSaV.App\\Twig\\Components\\ActionForm'] = $instance;
    }
}
