<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccountDeletionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\User\AccountDeletionController' shared autowired service.
     *
     * @return \App\Controller\User\AccountDeletionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/User/AccountDeletionController.php';

        $container->services['App\\Controller\\User\\AccountDeletionController'] = $instance = new \App\Controller\User\AccountDeletionController(($container->privates['App\\Services\\RGPD\\AccountDeletionService'] ?? self::getAccountDeletionServiceService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\User\\AccountDeletionController', $container));

        return $instance;
    }
}
