<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionCrudControllerconfigureAssetsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4g8KBWG.App\Controller\Admin\Action\ActionCrudController::configureAssets()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4g8KBWG.App\\Controller\\Admin\\Action\\ActionCrudController::configureAssets()'] = ($container->privates['.service_locator.4g8KBWG'] ?? $container->load('get_ServiceLocator_4g8KBWGService'))->withContext('App\\Controller\\Admin\\Action\\ActionCrudController::configureAssets()', $container);
    }
}
