<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComponentValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Symfony\UX\LiveComponent\ComponentValidator' shared service.
     *
     * @return \Symfony\UX\LiveComponent\ComponentValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/ComponentValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/ComponentValidator.php';

        $instance = new \Symfony\UX\LiveComponent\ComponentValidator((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'validator' => '?',
        ]))->withContext('Symfony\\UX\\LiveComponent\\ComponentValidator', $container));

        if (isset($container->privates['Symfony\\UX\\LiveComponent\\ComponentValidator'])) {
            return $container->privates['Symfony\\UX\\LiveComponent\\ComponentValidator'];
        }

        return $container->privates['Symfony\\UX\\LiveComponent\\ComponentValidator'] = $instance;
    }
}
