<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCronCheckCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\Cron\CronCheckCommand' shared autowired service.
     *
     * @return \App\Command\Cron\CronCheckCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Cron/CronCheckCommand.php';

        $container->privates['App\\Command\\Cron\\CronCheckCommand'] = $instance = new \App\Command\Cron\CronCheckCommand();

        $instance->setName('app:cron-check');
        $instance->setDescription('Commande de vérification du bon fonctionnement des tâches cron');

        return $instance;
    }
}
