<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\Dashboard\DashboardService' shared autowired service.
     *
     * @return \App\Services\Dashboard\DashboardService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Dashboard/DashboardService.php';
        include_once \dirname(__DIR__, 4).'/src/Services/User/UserSeniorityService.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Dashboard/DashboardDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Dashboard/DashboardDataProvider.php';

        $a = ($container->privates['App\\Services\\User\\UserValidationService'] ?? $container->load('getUserValidationServiceService'));

        if (isset($container->privates['App\\Services\\Dashboard\\DashboardService'])) {
            return $container->privates['App\\Services\\Dashboard\\DashboardService'];
        }

        $instance = new \App\Services\Dashboard\DashboardService($a, new \App\Services\User\UserSeniorityService(), ($container->privates['App\\Services\\Logbook\\LogbookProgressService'] ??= new \App\Services\Logbook\LogbookProgressService()), new \App\Services\Dashboard\DashboardDataProvider(($container->privates['App\\Repository\\LogbookRepository'] ?? self::getLogbookRepositoryService($container))));

        if (isset($container->privates['App\\Services\\Dashboard\\DashboardService'])) {
            return $container->privates['App\\Services\\Dashboard\\DashboardService'];
        }

        return $container->privates['App\\Services\\Dashboard\\DashboardService'] = $instance;
    }
}
