<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlasher_SweetalertService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'flasher.sweetalert' shared service.
     *
     * @return \Flasher\SweetAlert\Prime\SweetAlert
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/php-flasher/flasher/Factory/NotificationFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-flasher/flasher/Factory/NotificationFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-flasher/flasher-sweetalert/SweetAlertInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-flasher/flasher-sweetalert/SweetAlert.php';

        return $container->services['flasher.sweetalert'] = new \Flasher\SweetAlert\Prime\SweetAlert(($container->privates['flasher.storage_manager'] ?? self::getFlasher_StorageManagerService($container)));
    }
}
