<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedbackControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OSbtNXK.App\Controller\App\Dashboard\FeedbackController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feedbackRepository' => ['privates', 'App\\Repository\\FeedbackRepository', 'getFeedbackRepositoryService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'feedbackRepository' => 'App\\Repository\\FeedbackRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\App\\Dashboard\\FeedbackController::index()', $container);

        if (isset($container->privates['.service_locator.OSbtNXK.App\\Controller\\App\\Dashboard\\FeedbackController::index()'])) {
            return $container->privates['.service_locator.OSbtNXK.App\\Controller\\App\\Dashboard\\FeedbackController::index()'];
        }

        return $container->privates['.service_locator.OSbtNXK.App\\Controller\\App\\Dashboard\\FeedbackController::index()'] = $instance;
    }
}
