<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedbackControllerdetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DOCWs13.App\Controller\App\Dashboard\FeedbackController::detail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DOCWs13.App\\Controller\\App\\Dashboard\\FeedbackController::detail()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feedback' => ['privates', '.errored..service_locator.DOCWs13.App\\Entity\\Feedback', NULL, 'Cannot autowire service ".service_locator.DOCWs13": it needs an instance of "App\\Entity\\Feedback" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'feedback' => 'App\\Entity\\Feedback',
        ]))->withContext('App\\Controller\\App\\Dashboard\\FeedbackController::detail()', $container);
    }
}
