<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportUsersCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ImportUsersCommand' shared autowired service.
     *
     * @return \App\Command\ImportUsersCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ImportUsersCommand.php';

        $container->privates['App\\Command\\ImportUsersCommand'] = $instance = new \App\Command\ImportUsersCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:import-users');
        $instance->setDescription('Importe les utilisateurs depuis un fichier JSON d\'export PHPMyAdmin');

        return $instance;
    }
}
