<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogbookTemplateCrudControllerpersistEntityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3BoFVFw.App\Controller\Admin\Logbook_Models\LogbookTemplateCrudController::persistEntity()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3BoFVFw.App\\Controller\\Admin\\Logbook_Models\\LogbookTemplateCrudController::persistEntity()'] = ($container->privates['.service_locator.3BoFVFw'] ?? $container->load('get_ServiceLocator_3BoFVFwService'))->withContext('App\\Controller\\Admin\\Logbook_Models\\LogbookTemplateCrudController::persistEntity()', $container);
    }
}
