<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogbookReplacementServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\Logbook\LogbookReplacementService' shared autowired service.
     *
     * @return \App\Services\Logbook\LogbookReplacementService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Logbook/LogbookReplacementService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Services\\Logbook\\LogbookReplacementService'])) {
            return $container->privates['App\\Services\\Logbook\\LogbookReplacementService'];
        }

        $instance = new \App\Services\Logbook\LogbookReplacementService($a);

        if (isset($container->privates['App\\Services\\Logbook\\LogbookReplacementService'])) {
            return $container->privates['App\\Services\\Logbook\\LogbookReplacementService'];
        }

        return $container->privates['App\\Services\\Logbook\\LogbookReplacementService'] = $instance;
    }
}
