<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogbookCreationSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\LogbookCreationSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\LogbookCreationSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/LogbookCreationSubscriber.php';

        $a = ($container->privates['App\\Services\\Logbook\\LogbookReplacementService'] ?? $container->load('getLogbookReplacementServiceService'));

        if (isset($container->privates['App\\EventSubscriber\\LogbookCreationSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\LogbookCreationSubscriber'];
        }

        $instance = new \App\EventSubscriber\LogbookCreationSubscriber($a, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Repository\\LogbookRepository'] ?? self::getLogbookRepositoryService($container)));

        if (isset($container->privates['App\\EventSubscriber\\LogbookCreationSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\LogbookCreationSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\LogbookCreationSubscriber'] = $instance;
    }
}
