<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Mail_Testing\MailController' shared autowired service.
     *
     * @return \App\Controller\Mail_Testing\MailController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Mail_Testing/MailController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Mail/MentorReminderEmailService.php';

        $container->services['App\\Controller\\Mail_Testing\\MailController'] = $instance = new \App\Controller\Mail_Testing\MailController(($container->privates['App\\Services\\Logbook\\LogbookProgressService'] ??= new \App\Services\Logbook\LogbookProgressService()), ($container->privates['App\\Repository\\LogbookRepository'] ?? self::getLogbookRepositoryService($container)), ($container->privates['App\\Services\\Mail\\MentorReminderEmailService'] ??= new \App\Services\Mail\MentorReminderEmailService()));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Mail_Testing\\MailController', $container));

        return $instance;
    }
}
