<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentorDashboardControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\App\Dashboard\Mentor\MentorDashboardController' shared autowired service.
     *
     * @return \App\Controller\App\Dashboard\Mentor\MentorDashboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/App/Dashboard/Mentor/MentorDashboardController.php';

        $container->services['App\\Controller\\App\\Dashboard\\Mentor\\MentorDashboardController'] = $instance = new \App\Controller\App\Dashboard\Mentor\MentorDashboardController(($container->privates['App\\Services\\Mentor\\MentorService'] ?? $container->load('getMentorServiceService')), ($container->privates['App\\Services\\User\\UserValidationService'] ?? $container->load('getUserValidationServiceService')), ($container->privates['App\\Services\\Logbook\\LogbookProgressService'] ??= new \App\Services\Logbook\LogbookProgressService()));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\App\\Dashboard\\Mentor\\MentorDashboardController', $container));

        return $instance;
    }
}
