<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentorLogbookControllerdetailsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iuuhNp4.App\Controller\App\Dashboard\Mentor\MentorLogbookController::details()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iuuhNp4.App\\Controller\\App\\Dashboard\\Mentor\\MentorLogbookController::details()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'logbook' => ['privates', '.errored..service_locator.iuuhNp4.App\\Entity\\Logbook', NULL, 'Cannot autowire service ".service_locator.iuuhNp4": it needs an instance of "App\\Entity\\Logbook" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'logbook' => 'App\\Entity\\Logbook',
        ]))->withContext('App\\Controller\\App\\Dashboard\\Mentor\\MentorLogbookController::details()', $container);
    }
}
