<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_SchedulerTaskEmailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.transport.scheduler_task_email' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Receiver/ReceiverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Sender/SenderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportInterface.php';

        $a = ($container->privates['messenger.transport_factory'] ?? $container->load('getMessenger_TransportFactoryService'));

        if (isset($container->privates['messenger.transport.scheduler_task_email'])) {
            return $container->privates['messenger.transport.scheduler_task_email'];
        }

        $instance = $a->createTransport('schedule://task_email', ['transport_name' => 'scheduler_task_email'], ($container->privates['.signing.messenger.default_serializer'] ?? $container->load('get_Signing_Messenger_DefaultSerializerService')));

        if (isset($container->privates['messenger.transport.scheduler_task_email'])) {
            return $container->privates['messenger.transport.scheduler_task_email'];
        }

        return $container->privates['messenger.transport.scheduler_task_email'] = $instance;
    }
}
