<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgressControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\Progress\ProgressController' shared autowired service.
     *
     * @return \App\Controller\Admin\Progress\ProgressController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/Progress/ProgressController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/ProgressTrackingServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Progress/ProgressTrackingService.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/LogbookDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Logbooks/LogbookDataProvider.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/StatisticsServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Statistics/StatisticsService.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/ThemeProgressServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Themes/ThemeProgressService.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/ProgressAccessServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Progress/ProgressAccessService.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/UserProgressServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Users/UserProgressService.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/interfaces/FeedbackServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Admin/Feedbacks/FeedbackService.php';

        $a = ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService'));
        $b = ($container->privates['App\\Repository\\LogbookRepository'] ?? self::getLogbookRepositoryService($container));
        $c = ($container->privates['App\\Repository\\ActionRepository'] ?? self::getActionRepositoryService($container));

        $d = new \App\Services\Admin\Logbooks\LogbookDataProvider($b, $c);
        $e = ($container->privates['App\\Repository\\FeedbackRepository'] ?? self::getFeedbackRepositoryService($container));
        $f = ($container->privates['App\\Services\\Logbook\\LogbookProgressService'] ??= new \App\Services\Logbook\LogbookProgressService());
        $g = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));
        $h = new \App\Services\Admin\Progress\ProgressAccessService($g);
        $i = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        $container->services['App\\Controller\\Admin\\Progress\\ProgressController'] = $instance = new \App\Controller\Admin\Progress\ProgressController(new \App\Services\Admin\Progress\ProgressTrackingService($a, $d, new \App\Services\Admin\Statistics\StatisticsService($a, $e, $f, $d, $g), new \App\Services\Admin\Themes\ThemeProgressService(($container->privates['App\\Repository\\ThemeRepository'] ?? $container->load('getThemeRepositoryService')), $a, $c), $h, $f, $i), $h, new \App\Services\Admin\Users\UserProgressService($b, $f, $h, ($container->privates['twig'] ?? self::getTwigService($container)), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))), new \App\Services\Admin\Feedbacks\FeedbackService($e, $i));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Admin\\Progress\\ProgressController', $container));

        return $instance;
    }
}
