<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgressControllergenerateWorkbookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PtMLGj3.App\Controller\Admin\Progress\ProgressController::generateWorkbook()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PtMLGj3.App\\Controller\\Admin\\Progress\\ProgressController::generateWorkbook()'] = ($container->privates['.service_locator.PtMLGj3'] ?? $container->load('get_ServiceLocator_PtMLGj3Service'))->withContext('App\\Controller\\Admin\\Progress\\ProgressController::generateWorkbook()', $container);
    }
}
