<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\App\Pages\PagesController' shared autowired service.
     *
     * @return \App\Controller\App\Pages\PagesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/App/Pages/PagesController.php';

        $container->services['App\\Controller\\App\\Pages\\PagesController'] = $instance = new \App\Controller\App\Pages\PagesController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\App\\Pages\\PagesController', $container));

        return $instance;
    }
}
