<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessDeletionRequestsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ProcessDeletionRequestsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ProcessDeletionRequestsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:process-deletion-requests', [], 'Traite les demandes de suppression de compte expirées (délai de 48h dépassé)', false, #[\Closure(name: 'App\\Command\\ProcessDeletionRequestsCommand')] fn (): \App\Command\ProcessDeletionRequestsCommand => ($container->privates['App\\Command\\ProcessDeletionRequestsCommand'] ?? $container->load('getProcessDeletionRequestsCommandService')));
    }
}
