<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPushFixturesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\PushFixturesCommand' shared autowired service.
     *
     * @return \App\Command\PushFixturesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/PushFixturesCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Datas/DataLoader.php';

        $container->privates['App\\Command\\PushFixturesCommand'] = $instance = new \App\Command\PushFixturesCommand(new \App\Services\Datas\DataLoader(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))));

        $instance->setName('app:push-prod-fixtures');
        $instance->setDescription('Charge les fixtures Theme et Module en production');

        return $instance;
    }
}
