<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerlogoutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k5ChnDl.App\Controller\Security\SecurityController::logout()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'urlGenerator' => '?',
            'tokenStorage' => '?',
        ]))->withContext('App\\Controller\\Security\\SecurityController::logout()', $container);

        if (isset($container->privates['.service_locator.k5ChnDl.App\\Controller\\Security\\SecurityController::logout()'])) {
            return $container->privates['.service_locator.k5ChnDl.App\\Controller\\Security\\SecurityController::logout()'];
        }

        return $container->privates['.service_locator.k5ChnDl.App\\Controller\\Security\\SecurityController::logout()'] = $instance;
    }
}
