<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecialityRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\SpecialityRepository' shared autowired service.
     *
     * @return \App\Repository\SpecialityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/SpecialityRepository.php';

        return $container->privates['App\\Repository\\SpecialityRepository'] = new \App\Repository\SpecialityRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
