<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ThemeFormType' shared autowired service.
     *
     * @return \App\Form\ThemeFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ThemeFormType.php';

        return $container->privates['App\\Form\\ThemeFormType'] = new \App\Form\ThemeFormType();
    }
}
