<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeCrudControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\Theme\ThemeCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\Theme\ThemeCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/CrudControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractCrudController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/Theme/ThemeCrudController.php';

        $instance = new \App\Controller\Admin\Theme\ThemeCrudController();

        if (isset($container->services['App\\Controller\\Admin\\Theme\\ThemeCrudController'])) {
            return $container->services['App\\Controller\\Admin\\Theme\\ThemeCrudController'];
        }

        $container->services['App\\Controller\\Admin\\Theme\\ThemeCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.t0DHw4I'] ?? $container->load('get_ServiceLocator_T0DHw4IService'))->withContext('App\\Controller\\Admin\\Theme\\ThemeCrudController', $container));

        return $instance;
    }
}
