<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDataExportControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\User\UserDataExportController' shared autowired service.
     *
     * @return \App\Controller\User\UserDataExportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/User/UserDataExportController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/RGPD/UserDataExportService.php';

        $container->services['App\\Controller\\User\\UserDataExportController'] = $instance = new \App\Controller\User\UserDataExportController(new \App\Services\RGPD\UserDataExportService(($container->privates['twig'] ?? self::getTwigService($container)), ($container->privates['App\\Repository\\LogbookRepository'] ?? self::getLogbookRepositoryService($container)), ($container->privates['App\\Repository\\ActionRepository'] ?? self::getActionRepositoryService($container)), ($container->privates['App\\Repository\\FeedbackRepository'] ?? self::getFeedbackRepositoryService($container))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\User\\UserDataExportController', $container));

        return $instance;
    }
}
