<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserValidationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\User\UserValidationService' shared autowired service.
     *
     * @return \App\Services\User\UserValidationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/User/UserValidationService.php';

        $a = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->privates['App\\Services\\User\\UserValidationService'])) {
            return $container->privates['App\\Services\\User\\UserValidationService'];
        }

        $instance = new \App\Services\User\UserValidationService(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), $a);

        if (isset($container->privates['App\\Services\\User\\UserValidationService'])) {
            return $container->privates['App\\Services\\User\\UserValidationService'];
        }

        return $container->privates['App\\Services\\User\\UserValidationService'] = $instance;
    }
}
