<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_MetadataFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.live_component.metadata_factory' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Metadata\LiveComponentMetadataFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/Metadata/LiveComponentMetadataFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/type-info/TypeResolver/TypeResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/type-info/TypeResolver/TypeResolver.php';

        $a = ($container->privates['ux.twig_component.component_factory'] ?? $container->load('getUx_TwigComponent_ComponentFactoryService'));

        if (isset($container->privates['ux.live_component.metadata_factory'])) {
            return $container->privates['ux.live_component.metadata_factory'];
        }

        $instance = new \Symfony\UX\LiveComponent\Metadata\LiveComponentMetadataFactory($a, ($container->privates['property_info'] ?? self::getPropertyInfoService($container)), new \Symfony\Component\TypeInfo\TypeResolver\TypeResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'string' => ['privates', 'type_info.resolver.string', 'getTypeInfo_Resolver_StringService', true],
            'ReflectionParameter' => ['privates', 'type_info.resolver.reflection_parameter.phpdoc_aware', 'getTypeInfo_Resolver_ReflectionParameter_PhpdocAwareService', true],
            'ReflectionProperty' => ['privates', 'type_info.resolver.reflection_property.phpdoc_aware', 'getTypeInfo_Resolver_ReflectionProperty_PhpdocAwareService', true],
            'ReflectionFunctionAbstract' => ['privates', 'type_info.resolver.reflection_return.phpdoc_aware', 'getTypeInfo_Resolver_ReflectionReturn_PhpdocAwareService', true],
            'ReflectionType' => ['privates', 'type_info.resolver.reflection_type', 'getTypeInfo_Resolver_ReflectionTypeService', true],
        ], [
            'string' => '?',
            'ReflectionParameter' => '?',
            'ReflectionProperty' => '?',
            'ReflectionFunctionAbstract' => '?',
            'ReflectionType' => '?',
        ])));

        if (isset($container->privates['ux.live_component.metadata_factory'])) {
            return $container->privates['ux.live_component.metadata_factory'];
        }

        return $container->privates['ux.live_component.metadata_factory'] = $instance;
    }
}
