<?php

namespace Container0f07r9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCrudControllerdeleteUserOnlyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u80UfP3.App\Controller\Admin\User\UserCrudController::deleteUserOnly()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.u80UfP3'] ?? $container->load('get_ServiceLocator_U80UfP3Service'));

        if (isset($container->privates['.service_locator.u80UfP3.App\\Controller\\Admin\\User\\UserCrudController::deleteUserOnly()'])) {
            return $container->privates['.service_locator.u80UfP3.App\\Controller\\Admin\\User\\UserCrudController::deleteUserOnly()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\User\\UserCrudController::deleteUserOnly()', $container);

        if (isset($container->privates['.service_locator.u80UfP3.App\\Controller\\Admin\\User\\UserCrudController::deleteUserOnly()'])) {
            return $container->privates['.service_locator.u80UfP3.App\\Controller\\Admin\\User\\UserCrudController::deleteUserOnly()'];
        }

        return $container->privates['.service_locator.u80UfP3.App\\Controller\\Admin\\User\\UserCrudController::deleteUserOnly()'] = $instance;
    }
}
