name: Quality Analysis
on: [push, pull_request]
jobs:
  quality:
    name: Quality Analysis
    runs-on: ubuntu-latest
    container:
      image: jakzal/phpqa:php8.2
      options: --user root
    steps:
      - name: Set safe directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          chown -R $(id -u):$(id -g) "$GITHUB_WORKSPACE"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XSL extension
        run: |
          apt-get update
          apt-get install -y libxslt-dev
          docker-php-ext-install xsl

      - name: Setup Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Caching deps
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.2-composer-${{ hashfiles('**/composer.json') }}
          restore-keys: |
            php8.2-composer-latest-

      - name: Validate composer.json
        run: composer validate --strict

      - name: install deps
        run: |
          composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: PHP-CS-Fixer
        run: |
          wget https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/download/v3.59.3/php-cs-fixer.phar -O php-cs-fixer
          chmod +x php-cs-fixer
          ./php-cs-fixer fix ./src --rules=@Symfony --verbose --dry-run

      - name: PHPStan
        run: phpstan analyse --configuration=phpstan.neon

      - name: PHPCPD
        run: phpcpd ./src

      - name: Lint YAML
        run: php bin/console lint:yaml config

      - name: Lint Twig
        run: php bin/console lint:twig templates

      - name: Lint Container
        run: php bin/console lint:container
