name: Tests
on: [push, pull_request]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.11
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: db_compagnonnage
        ports:
          - 3306:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          extensions: pdo, pdo_mysql

      - name: Install deps
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Wait for MariaDB
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" -uroot -proot --silent; do
            sleep 2
          done

      - name: Database Creation
        run: |
          php bin/console cache:clear --env=test
          php bin/console doctrine:database:drop --force --env=test --if-exists
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:update --env=test --force
        env:
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/db_compagnonnage?serverVersion=mariadb-10.11.0"

      - name: Tests
        run: |
          vendor/bin/phpunit --testdox --colors=always --display-warnings --display-errors
        env:
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/db_compagnonnage?serverVersion=mariadb-10.11.0"
          APP_ENV: test
          KERNEL_CLASS: 'App\Kernel'
          SYMFONY_DEPRECATIONS_HELPER: disabled
