name: Tests
on: [push, pull_request]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      database:
        image: mariadb:latest
        env:
          MYSQL_DATABASE: db_compagnonnage
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          extensions: pdo, pdo_mysql

      - name: Install deps
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Wait for database
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"${{ job.services.database.ports['3306'] }}" --silent; do
            sleep 1
          done

      - name: Database Creation
        run: |
          php bin/console cache:clear --env=test
          php bin/console doctrine:database:drop --force --env=test --if-exists
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:update --env=test --force

      - name: Tests
        run: |
          php vendor/phpunit/phpunit/phpunit --colors=always
